platform :ios, '8.0'

target 'GTModuleLibrary' do
  use_frameworks!

  #网络请求库
  pod 'YTKNetwork'

  #组件化工具
  pod 'BeeHive'

  #路由工具
  pod 'JLRoutes'

  #布局工具
  pod 'Masonry'

  #图片工具
  pod 'SDWebImage'

  #网络监控工具
  pod 'RealReachability'

  #提示工具
  pod 'MBProgressHUD'

  #数据库工具
  pod 'FMDB'


end
